# fly.toml app configuration file generated for grpc-hello-world on 2024-10-08T14:11:36+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grpc-hello-world'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 50051
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
